runs_dir: output
seed: 0
frames: 30

stable_diffusion_checkpoint: "emily49/barbie-stable-diffusion-non-inpaint-1-5" #"dreambooth_models/mountains-sks-1500"

inpainting_prompt: "POV, walkthrough, dreamhouse from sks barbie, masterpiece, indoor scene, best quality"
