runs_dir: output
seed: 0
frames: 30

stable_diffusion_checkpoint: "emily49/frozen-stable-diffusion-non-inpaint-1-5" #"dreambooth_models/mountains-sks-1500"
first_stable_diffusion_checkpoint: "emily49/frozen-stable-diffusion-non-inpaint-1-5"

inpainting_prompt: "POV, walkthrough, castle from sks frozen, masterpiece, indoor scene, best quality"
first_inpainting_prompt: "POV, walkthrough, castle from sks frozen, masterpiece, indoor scene, best quality"
