runs_dir: output
seed: 0
frames: 30

stable_diffusion_checkpoint: "emily49/harry-potter-stable-diffusion-non-inpaint-1-5" #"dreambooth_models/mountains-sks-1500"

inpainting_prompt: "POV, walkthrough, castle from sks harrypotter, masterpiece, indoor scene, best quality"
