runs_dir: output
seed: 2
frames: 30

stable_diffusion_checkpoint: "emily49/spirited-away-stable-diffusion-non-inpaint-1-5" #"dreambooth_models/mountains-sks-1500"

inpainting_prompt: "POV, walkthrough, train from sks spiritedaway, masterpiece, indoor scene, best quality"
